services:

  ### Workspace #########################################
  workspace:
    build: 
      context: .
      dockerfile: ./docker/workspace/Dockerfile
    volumes:
      - ./:/workspace
      - node-module-volume:/workspace/app/node_modules
    working_dir: /workspace
    ports:
      - "5173:5173"
    init: true
    tty: true
    stdin_open: true

volumes:
  node-module-volume:
