version: '3.9'
services:

  ### App #########################################
  app:
    image: node:21-bookworm
    volumes:
      # - ./app:/app
      # - node-module-volume:/app/node_modules
      - ./:/workspace
      - node-module-volume:/workspace/app/node_modules
    working_dir: /workspace
    ports:
      - "8085:8085"
    init: true
    tty: true
    stdin_open: true

volumes:
  node-module-volume:
